//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dBosque.Stub.EF.Interceptor.TestClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public int MessageTypeID { get; set; }
        public string Namespace { get; set; }
        public string Rootnode { get; set; }
        public string Description { get; set; }
        public bool PassthroughEnabled { get; set; }
        public string PassthroughUrl { get; set; }
        public string Sample { get; set; }
    }
}
